### ISSUE TITLE
build failure for pypy3 - related with zope.interface

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/z3c.autoinclude#14]
https://travis-ci.org/github/zopefoundation/z3c.autoinclude/jobs/659915396

Maybe @jamadden can give a hint?

**Comment by jamadden** [comment]
The error:
```
WARNING: The easy_install command is deprecated and will be removed in a future version.
Traceback (most recent call last):
  File "/home/travis/build/zopefoundation/z3c.autoinclude/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/travis/build/zopefoundation/z3c.autoinclude/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/travis/build/zopefoundation/z3c.autoinclude/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-temqwlfr/zope.interface-4.7.1/setup.py", line 26, in <module>
ImportError: cannot import name 'Feature'
```

Shows that the buildout is picking the wrong version of `zope.interface`, one too old to work with the versions of `setuptools` that was picked. Dunno why.

**Comment by jugmac00** [comment]
Tests run successfully now... for reasons.
